### ISSUE TITLE
Black Screen, sound playing on games ( AMD) ( log)

### ISSUE THREAD

**Issue by ankoku66** [decaf-emu/decaf-emu#333] opened 2016-08-20 15:11 UTC
[one piece_2016-08-20_11-46.txt](https://github.com/decaf-emu/decaf-emu/files/428369/one.piece_2016-08-20_11-46.txt)

tested on:
-Decaf-20160820-x64
no image ( black) 
sound: yes

r9 270x a10 6800k 8gb ram
latest drivers installed

**Comment by ikki84** [comment] 2016-08-20 19:49
Could you test Shovel Knight with your amd videocard? 
I think its also not rendering anything, just playing the game´s sound.

**Comment by ankoku66** [comment] 2016-08-20 20:54
oikok ill download it and test. This op works on cemu ( max fps no sound)

**Comment by ankoku66** [comment] 2016-08-20 21:05
[Shovel Knight (USA)_2016-08-20_18-03.txt](https://github.com/decaf-emu/decaf-emu/files/428498/Shovel.Knight.USA._2016-08-20_18-03.txt)

Same thing, black screen and just playing the sound :v

**Comment by Adubbz** [comment] 2016-08-20 22:57
It sounds like this may be the same issue as https://github.com/decaf-emu/decaf-emu/issues/317

**Comment by ankoku66** [comment] 2016-08-20 23:00
i think so, he has amd too, i saw his video bfore. ive tried reinstalling drivers and with different decaf. ( >_<)

**Comment by brett19** [comment] 2016-08-20 23:20
Closing as duplicate of #317

**Closed by brett19** 2016-08-20 23:20 UTC
