### ISSUE TITLE
OpenGL issues on AMD and Nvidia hardware*

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [decaf-emu/decaf-emu#317] opened 2016-08-18 21:10 UTC
The Game loads i see the small Blue loading bar and than it goes black http://pastebin.com/uUWeH1F5 here is the log now the issue is a friend loads the game and get's in game with most things rendering as seen here https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vaS5pbWd1ci5jb20vM0piWEVKbi5qcGcifQ.OcktoL9iAQKkG47i4ac0MzwqLB4.jpg?width=2000&height=1093 and his log is here http://hastebin.com/raw/ecelomewas
 any help would be great or if i made you aware of a issue that's fine also

**Comment by Gamedev1909** [comment] 2016-08-20 00:07
[04:38.856492 warning:6656] Unusual shader with a fully masked export
[04:40.164273 warning:6656] Unusual shader with a fully masked export
[04:40.355465 warning:6656] Ignoring early-Z because shader writes gl_FragDepth
[04:40.415603 warning:6656] Unusual shader with a fully masked export
[04:41.857818 warning:6656] Export is masked by cb_shader_mask
[04:41.929912 warning:6656] Export is masked by cb_shader_mask
[04:42.102559 warning:6656] Unusual shader with a fully masked export
[04:42.553856 warning:6656] Export is masked by cb_shader_mask
[04:43.039302 warning:6656] Ignoring early-Z because shader writes gl_FragDepth
[04:43.274983 error:6656] OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(423, 0, 0, 0, 0, 64, 64, 6, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT, 12288, 00000206DE75AEA0)
[04:43.275695 warning:6656] Export is masked by cb_shader_mask
[04:43.317784 warning:6656] Unusual shader with a fully masked export
[04:43.909062 warning:6656] Export is masked by cb_shader_mask
[04:44.757219 error:6656] OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(494, 0, 0, 0, 0, 32, 32, 6, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT, 3072, 00000206DC4C0250)
[04:44.757533 error:6656] OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(495, 0, 0, 0, 0, 64, 64, 6, GL_COMPRESSED_RGBA_S3TC_DXT3_EXT, 24576, 00000206DF08BA40)
[04:45.578755 warning:6656] Unusual shader with a fully masked export 



i get this now

**Comment by Gamedev1909** [comment] 2016-08-20 01:29
https://www.youtube.com/watch?v=MryL1R3B85I here is a video if that helps

**Comment by Gamedev1909** [comment] 2016-08-22 16:16
if you guys need anything else do ask i want to fix this issue as soon as possible

**Comment by exjam** [comment] 2016-08-22 16:21
This will not be fixed until a developer who has an AMD card appears and fixes the issues. I wouldn't expect that any time soon.

**Comment by Gamedev1909** [comment] 2016-08-22 16:24
the issue isnt just amd a person in my discord with nvidia has the same issue as me and if need be i can let you guys use my pc to do test and fix the issue because amd uses opengl the same way as everyone else

**Comment by RHY3756547** [comment] 2016-08-22 16:50
> amd uses opengl the same way as everyone else
If it did, then we wouldn't be having this issue... 

Things look fine for me with 680 GTX on the latest driver, and NVIDIA cards are rarely different. Try telling them to update their drivers.

**Comment by Gamedev1909** [comment] 2016-08-22 16:52
they always do the 700-900 cards are hugly diffeant from each other by the way somethings added and removed and some handle opengl diffeant as well

**Comment by RHY3756547** [comment] 2016-08-22 16:57
Works fine on 800 series here too. What's the problematic GPU?

**Comment by Gamedev1909** [comment] 2016-08-22 17:00
970 as always garbage of a card

**Comment by exjam** [comment] 2016-08-22 17:09
I have a GTX970, and obviously I have no problems - I am running the latest drivers.

As I said before - there is no point in spamming this issue because we do not have the hardware to reproduce the bugs. This is an in-development project - we do not guarantee compatibility with any hardware or software. Unless a developer comes along and fixes these problems this issue will remain unsolved.

**Comment by Gamedev1909** [comment] 2016-08-22 17:20
and as i said i will let you use my hardware to fix the issue throught team viewer as i have fibre op so it will be like working in real time and i have everything ready to go

**Comment by Gamedev1909** [comment] 2016-08-23 03:33
[XCX_2016-08-23_03-24.txt](https://github.com/decaf-emu/decaf-emu/files/431632/XCX_2016-08-23_03-24.txt)
that's from the newest build it might help

**Comment by Gamedev1909** [comment] 2016-08-23 22:26
[XCX_2016-08-23_22-23.txt](https://github.com/decaf-emu/decaf-emu/files/433674/XCX_2016-08-23_22-23.txt)
[MarioKart8_2016-08-23_22-23.txt](https://github.com/decaf-emu/decaf-emu/files/433675/MarioKart8_2016-08-23_22-23.txt)
tested newest build i get a crash on XCX now but DKTF get's farther

**Comment by Gamedev1909** [comment] 2016-08-24 15:48
[XCX_2016-08-24_15-43.txt](https://github.com/decaf-emu/decaf-emu/files/435090/XCX_2016-08-24_15-43.txt) with newest build more things changed

**Comment by ankoku66** [comment] 2016-08-24 16:33
xcx works for you with amd ? ive tried again shovel knight and one piece still have black screen ( which driver you have?)

**Comment by RHY3756547** [comment] 2016-08-24 17:07
Not getting these on nvidia:
```
//connecting screen
OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(11, 0, 0, 0, 0, 32, 32, 6, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT, 3072, 0000021ABE93D430)
OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(12, 0, 0, 0, 0, 64, 64, 6, GL_COMPRESSED_RGBA_S3TC_DXT3_EXT, 24576, 0000021ABE96FF80)
//title screen
OpenGL error: GL_INVALID_OPERATION with glPauseTransformFeedback()
OpenGL error: GL_INVALID_VALUE with glCompressedTextureSubImage3D(234, 0, 0, 0, 0, 64, 64, 6, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT, 12288, 0000021AD23D84A0)
```
Can't be sure if they are directly related to every game showing a black screen though. OpenGL spec has this to say:

`GL_INVALID_VALUE is generated if imageSize is not consistent with the format, dimensions, and contents of the specified compressed image data.`

...but those numbers look correct to me.

**Comment by Gamedev1909** [comment] 2016-08-24 19:00
290x newest driver yes a black screen because opengl is failing to render like it should but for some reason it renders res evil and DKTF just fine but games like MK8 and XCX are bugged

**Comment by Gamedev1909** [comment] 2016-08-24 19:13
[XCX_2016-08-24_16-10.txt](https://github.com/decaf-emu/decaf-emu/files/435498/XCX_2016-08-24_16-10.txt)
newest build from 40 mins ago

**Comment by mikakev1** [comment] 2016-08-25 05:29
Hi, I can confirm this is happening on Windows 10 anniversary update with a R9270X (GCN1.0). 
However on ARCHLINUX (kernel 4.7.1, mesa 12.1) using radeonsi it goes way further and render. 
(Radeonsi is currently stuck to OGL 4.3CORE (see https://mesamatrix.net/), so I had to force GLSL430 and GL4.3CORE). It would be great to test with AMDGPUPRO driver with a GCN 1.2+ hardware.

**Comment by Gamedev1909** [comment] 2016-08-25 22:38
in windows amd has opengl 4.5 full c compatibility but it seems this is a
issue with opengl or the driver

**Comment by ankoku66** [comment] 2016-08-26 16:13
im getting this on the latest.

> 

 [11:27.136497 info:w108] Unimplemented kernel function padscore::WPADGetBatteryLevel called from 0x026A45F4
[11:27.147463 info:w113] Thread exiting, exit value is 0
[11:27.424017 critical:w108] Assertion failed:
Expression: internal::isThreadActiveNoLock(thread)
File: ..\src\libdecaf\src\modules\coreinit\coreinit_thread.cpp
Line: 292
Stacktrace:
6: SDL_SetClipboardText - 0x7FF7113251A0x

> 
``

**Comment by Gamedev1909** [comment] 2016-09-02 03:15
[xcx_2016-09-02_00-13.txt](https://github.com/decaf-emu/decaf-emu/files/451100/xcx_2016-09-02_00-13.txt)
with Pm4 trace enabled

**Comment by mikakev1** [comment] 2016-09-12 12:10
Hi, this is an issue related to DSA on AMD's implementation. glCompressedTextureSubImage3D/glTextureSubImage3D doesn't play well with GL_TEXTURE_CUBE_MAP.

**Comment by mikakev1** [comment] 2017-01-11 21:54
Mesa was updated and radeonsi, nouveau, intel,  now comply to OpenGL 4.5.
As a result the issue I had with amd card seems to have disapeared at last :)

**Comment by mikakev1** [comment] 2017-04-21 08:14
Actually one of the remaining issue is about to be fixed, ARB_bindless_texture is on its way on MESA.
You may be able still to workaround using recent KHR_no_error and/or by using driconf, set "default behaviour to warn", but I've not tested.
I fear that some ARB extension for AZDO, will be missing  if you do not use AMDGPU kernel driver, that received a lot of work lately.

**Comment by Gamedev1909** [comment] 2017-04-21 16:42
Its not all about linux ok its about windows also black screens are not fun on either side

**Comment by mikakev1** [comment] 2017-04-21 17:36
I do subscribe to what you say. Radeon have two big problems nowadays with OpenGL
- Many devs uses Nvidia
- AMD's drivers are quite a mess when it comes to OpenGL (Dual source blending lead to crash, ARB_separate_shader_object is wrong, GLSL parsing errors, etc... )
As RadeonSI, is becoming the preferred driver under GNU/Linux, it's possible it'll be the only options we have in the short term. We can only hope that Vulkan arises and restore the balance. I do not believe in DX12.

**Comment by Gamedev1909** [comment] 2017-04-21 18:05
Or the devs can ask exzap for help as he already fixed all the issues

**Comment by exjam** [comment] 2018-11-12 13:32
Hopefully this will be fixed by Vulkan. We will be deprecating the OpenGL backend soon.

**Closed by exjam** 2018-11-12 13:32 UTC
Labels: OpenGL
