### ISSUE TITLE
cafe/hle: StackReserveWrapper breaks coroutine stack switches.

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#551] opened 2019-04-23 14:50 UTC
`StackReserveWrapper` (in `cafe_hle_library_function.h`) pushes a stack frame before calling an HLE function and pops the frame afterwards. I assume this is to reserve storage space for a callee's LR in case the HLE routine calls back into PPC code, but this cancels any stack change made by `OSSwitchCoroutine()`. (I observed this in Xenoblade X, which crashed due to a null sync object pointer on the stack when another coroutine clobbered it instead of writing to its own stack.)

I was able to get things working by reading `core->gpr[1]` instead of reusing `backchainSp` when popping the stack frame, and adding a magic number to the frame and checking for it on return to avoid popping from an empty stack in a newly created coroutine. But this is obviously a kludge; maybe the "correct" solution is to wrap all HLE calls with stack frame setup/teardown on the PPC side?

**Comment by exjam** [comment] 2019-04-23 15:31
Ah yes, I did not think of OSSwitchCoroutine when i had the thought that all HLE functions should have a stack frame setup. If i remember correctly I did it so that StackObject had a proper stack frame to use?

We could come up with someway to enforce that any function which uses StackObject<x> or calls back to LLE (aka requires a stacke frame) allocates a stack frame.

Maybe require a StackFrame reference in constructor like:
```
StackFrame f;
StackObject<int> x { f };
```

I'll have to go back and think about this a bit more to make sure I am not missing any other reason for adding stack frame to every HLE.

**Comment by exjam** [comment] 2019-04-28 13:23
So I've been fiddling with a few ideas over the past few days...

First of all, different to how it is currently, I believe we only really need a stack frame / backchain when calling back into user code.

The stack we require when calling from user code -> HLE function -> user code would look like:
```
<Backchain to Caller Backchain>
<Stack args to user function>
<StackObjects for HLE function>
<Caller Backchain ...>
<Stack args to HLE function>
... etc
```

So if we left the backchain generation until cafe::invoke then StackObjects can just freely allocate stack without worrying about anything, but the problem is that on writing the backchain we will need to know the address of the backchain (which is the gpr[1] value at time of the HLE call before we allocate any stack objects). This makes things complicated for if we want to do something like I previously suggested with passing around some object, unless we just do a bit of a hack and set a field in the cpu::Core structure to the stack value at time of the system call HLE thing. It feels abit wrong to throw that into the cpu::Core struct but seems like the simplest option.

I'll push a change for that soon once I undo the mess I made of my codebase figuring this out and then test it. :)

**Comment by exjam** [comment] 2019-04-28 16:05
Fixed now with 
af7616100b5b9f55344d67b0872195692a6f9be7
58fc9dc3f8edb66bbd64305966c9f2dce4c9f69a
f706d9c585d7b44ea3ffc7f2b641d8b8980f1b4e

Unfortunately Xenoblade is now blocked on
https://github.com/decaf-emu/decaf-emu/issues/542

**Closed by exjam** 2019-04-28 16:05 UTC
