### ISSUE TITLE
GLSL translate exception: Uninplemented CF instruction 9 LOOP_BREAK

### ISSUE THREAD

**Issue by WilianZilv** [decaf-emu/decaf-emu#434] opened 2017-04-28 01:32 UTC
Atempt to boot Zelda Breath of the Wild.
Crashes in the "Nintendo presents" screen

[info] Loaded config from C:\Users\wilia\AppData\Roaming\decaf\config.toml
Assertion failed:
Expression: 0
File: C:\projects\decaf-emu\src\libgpu\src\glsl2\glsl2_translate.cpp
Line: 757
Message: GLSL translate exception: Unimplemented CF instruction 9 LOOP_BREAK
Stacktrace:
19:  - 0x0x
18:  - 0x0x
17:  - 0x0x
16: _C_specific_handler - 0x7FFA4F48C0B0x
15: _FrameUnwindFilter - 0x7FFA4F4825F0x
14: RtlCaptureContext - 0x7FFA667E9230x
13: RtlCaptureContext - 0x7FFA667E9230x
12: RtlCaptureContext - 0x7FFA667E9230x
11: RtlCaptureContext - 0x7FFA667E9230x
10: RtlCaptureContext - 0x7FFA667E9230x
9: RtlCaptureContext - 0x7FFA667E9230x
8: RtlCaptureContext - 0x7FFA667E9230x
7: RtlCaptureContext - 0x7FFA667E9230x
6: RtlCaptureContext - 0x7FFA667E9230x
5: RtlCaptureContext - 0x7FFA667E9230x
4: RtlCaptureContext - 0x7FFA667E9230x
3: RtlCaptureContext - 0x7FFA667E9230x
2: o__strtoui64 - 0x7FFA62D20310x
1: BaseThreadInitThunk - 0x7FFA65022760x
0: RtlUserThreadStart - 0x7FFA667B0D40x

**Comment by Adubbz** [comment] 2017-04-28 01:33
This is a dupe of https://github.com/decaf-emu/decaf-emu/issues/432

**Closed** 2017-04-28 04:11 UTC
